### ISSUE TITLE
Right Click -> Close session crashes hxScout

### ISSUE THREAD

**Issue by Tiago-Ling** [jcward/hxtelemetry#23]
Using version 0.4.0 on Windows 10 x64.

Whenever i try to close a session by right-clicking over it and choosing "Close session" the application crashes.

Since a new session is created every time a telemetry-enabled application is run, hxScout ends up having several sessions that cannot be closed.

Suggestion: Save sessions when closing hxScout, but do not bring them up again after closing and running it again. Instead, keep them in a folder and let the user choose any of them if they wish.

If possible the open dialog could show this default folder instead of opening the user's document folder.

**Comment by jcward** [comment]
Odd, I'll have to test delete on Windows, it's just deleting the files.

You can delete those temp session files manually - I believe on win and mac they may be in the hxScout directory `/temp` -- they're the `14########.hxt` files.

On Linux, they're in `~/.config/com.hxScout/temp/`

**Comment by jcward** [comment]
Note, Nico M reported the same behavior: https://twitter.com/nico_m__/status/650862072104792064

Also Windows

**Comment by jcward** [comment]
Resolved, will be in next release (> 0.4.0)

**Comment by Tiago-Ling** [comment]
Great job Jeff!
