### ISSUE TITLE
Making HxScout work with HaxeFlixel

### ISSUE THREAD

**Issue by sruloart** [jcward/hxtelemetry#30]
The example seems to be outdated (http://haxeflixel.com/forum/?place=msg%2Fhaxeflixel%2FwROYNz97fbE%2FOSD1Ua7uAwAJ), it should be pretty straight forward to set-up, but it's not for some reason :)

**Comment by jcward** [comment]
Thanks for the note -- yes, I'd believe my HxTelemetry HaxeFlixel example is out of date. But all that _should_ be necessary (for someone's HaxeFlixel project with recent libs) is add `-Dtelemetry` to the openfl command.

**Comment by jcward** [comment]
Ok, all I had to do was remove the outdated configuration from the HelloFlixel sample.
