### ISSUE TITLE
Compile fails /w -dce full (WRT compile_fails_without_this_function_definition)

### ISSUE THREAD

**Issue by ruby0x1** [jcward/hxtelemetry#34]
This was still failing for me until I added `@:keep` to the CppHxTelemetry class itself.

**Comment by jcward** [comment]
Thanks for the feedback, @underscorediscovery!

**Comment by ruby0x1** [comment]
Looking at this closer, since I ran into it in my own code:
The issue relates to your cpp code using Bytes without including the Bytes definition.

In other words, you're missing this line.
`#include <haxe/io/Bytes.h>`

Add it at inside your inline cpp or using the meta for cppFileHeader or similar and you should be good.
