### ISSUE TITLE
Android Build not working - CppHxTelemetry.cpp:219:31: error: incomplete type 'haxe::io::Bytes_obj'

### ISSUE THREAD

**Issue by sebthom** [jcward/hxtelemetry#35]
```
Error: ./src/hxtelemetry/CppHxTelemetry.cpp: In static member function 'static Void hxtelemetry::CppHxTelemetry_obj::dump_telemetry_frame(int, haxe::io::Output, Dynamic)':
./src/hxtelemetry/CppHxTelemetry.cpp:219:31: error: incomplete type 'haxe::io::Bytes_obj' used in nested name specifier
 ::haxe::io::Bytes bytes = ::haxe::io::Bytes_obj::alloc((int)size*4);
```

Haxe 3.2.0
OpenFL 3.4.0
hxtelemetry 0.3.2
Android NDK r10e

Console Output: [telemetry-compile-error.txt](https://github.com/jcward/hxtelemetry/files/49194/telemetry-compile-error.txt)

The Android Build works fine without HxTelemetry, i.e. when not specifying -Dtelemetry with openfl

**Comment by jcward** [comment]
Hmm, the missing definition is related to #34. I'm not sure I've pushed this fix to haxelib -- are you testing from haxelib or git?

If from haxelib, perhaps try using git:

```
haxelib git hxtelemetry https://github.com/jcward/hxtelemetry
```

If you're already using git, I'll have some more digging to do. Thanks for the feedback!

**Comment by sebthom** [comment]
Compiles with the version from trunk. Thanks!

**Comment by jcward** [comment]
Excellent, sorry for the hiccup. I've just submitted the latest to haxelib as 0.3.3.
