### ISSUE TITLE
Crashes at start, i have no idea what can be the problem

### ISSUE THREAD

**Issue by shadowofsoul** [jcward/hxtelemetry#38]
I spent 6 hours on this, and i discarded everything, i even started a blank project with just an sprite to make it work, unsuccessfully. 

for some reason, when it connects, immediately,  crashes. i compiled with:
`openfl 3.5.3 & lime 2.8.2`
`openfl 3.6.0 & lime 2.9.0`

all using hxcpp `3.2.205`

here i'm attaching the android monitor dump and a TCPdump log too. plus the example project

[hxscout-monitor-dump.txt](https://github.com/jcward/hxtelemetry/files/136988/hxscout-monitor-dump.txt)
[hxscout-tcpdump.txt](https://github.com/jcward/hxtelemetry/files/136989/hxscout-tcpdump.txt)

[testhxcout.zip](https://github.com/jcward/hxtelemetry/files/136992/testhxcout.zip)

**Comment by jcward** [comment]
Hi,

So you're testing on an Android device? Hmm, I might try disabling allocation tracking first. Sometimes allocation tracking causes problems (too many allocs, takes too long, etc.) Althought with an empty project that seems unlikely, but who knows.

So try `allocations="false"` in your `application.xml` file:

```
<config:hxtelemetry allocations="false" host="192.168.1.33" />
```

**Comment by shadowofsoul** [comment]
Disabling the allocations worked (in the empty project) thanks!, but there is any chance i could enable it? this depends of the android device or the desktop app? i need to figure out a memory leak, that's the main reason i need to use it.

**Comment by jcward** [comment]
Hmm, I've been meaning to add filtering to the allocation logic. It often tracks too many objects (even Floats), when we sometimes only care about our own classes. Desktop should certainly handle allocation tracking better, you might try that.

**Comment by shadowofsoul** [comment]
On my W7 workstation worked. BTW, on my virtualized W7 it crashed (hxScout, not the game) after game connected to hxScout. just to let you know. Thanks for all the help !
