### ISSUE TITLE
'__hxcpp_hxt_start_telemetry' : is not a member of '`global namespace''

### ISSUE THREAD

**Issue by smks** [jcward/hxtelemetry#39]
HxTelemetry.cpp
./src/hxtelemetry/HxTelemetry.cpp(382) : error C2039: '__hxcpp_hxt_start_telemetry' : is not a member of '`global namespace''
./src/hxtelemetry/HxTelemetry.cpp(382) : error C3861: '__hxcpp_hxt_start_telemetry': identifier not found
./src/hxtelemetry/HxTelemetry.cpp(548) : error C2039: '__hxcpp_hxt_ignore_allocs' : is not a member of '`global namespace''
./src/hxtelemetry/HxTelemetry.cpp(548) : error C3861: '__hxcpp_hxt_ignore_allocs': identifier not found
./src/hxtelemetry/HxTelemetry.cpp(660) : error C2039: '__hxcpp_hxt_ignore_allocs' : is not a member of '`global namespace''
./src/hxtelemetry/HxTelemetry.cpp(660) : error C3861: '__hxcpp_hxt_ignore_allocs': identifier not found
./src/hxtelemetry/HxTelemetry.cpp(682) : error C2039: '__hxcpp_hxt_ignore_allocs' : is not a member of '`global namespace''
./src/hxtelemetry/HxTelemetry.cpp(682) : error C3861: '__hxcpp_hxt_ignore_allocs': identifier not found
./src/hxtelemetry/HxTelemetry.cpp(778) : error C2039: '__hxcpp_hxt_ignore_allocs' : is not a member of '`global namespace''
./src/hxtelemetry/HxTelemetry.cpp(778) : error C3861: '__hxcpp_hxt_ignore_allocs': identifier not found
./src/hxtelemetry/HxTelemetry.cpp(1166) : error C2039: '__hxcpp_hxt_ignore_allocs' : is not a member of '`global namespace''
./src/hxtelemetry/HxTelemetry.cpp(1166) : error C3861: '__hxcpp_hxt_ignore_allocs': identifier not found
./src/hxtelemetry/HxTelemetry.cpp(1223) : error C2039: '__hxcpp_hxt_ignore_allocs' : is not a member of '`global namespace''
./src/hxtelemetry/HxTelemetry.cpp(1223) : error C3861: '__hxcpp_hxt_ignore_allocs': identifier not found
./src/hxtelemetry/HxTelemetry.cpp(1238) : error C2039: '__hxcpp_hxt_ignore_allocs' : is not a member of '`global namespace''
./src/hxtelemetry/HxTelemetry.cpp(1238) : error C3861: '__hxcpp_hxt_ignore_allocs': identifier not found
./src/hxtelemetry/HxTelemetry.cpp(1267) : error C2039: '__hxcpp_hxt_ignore_allocs' : is not a member of '`global namespace''
./src/hxtelemetry/HxTelemetry.cpp(1267) : error C3861: '__hxcpp_hxt_ignore_allocs': identifier not found

**Comment by jcward** [comment]
Hi,

I think this means your version of hxcpp isn't up to date. haxelib list
will show you what version you have. If I recall, you need version 3.2.171
or higher.

Let me know if that doesn't help you get it sorted.

Best,
-Jeff

**Comment by jcward** [comment]
Closing stale issue.
