### ISSUE TITLE
Startup crash when Scout is open

### ISSUE THREAD

**Issue by sh-dave** [jcward/hxtelemetry#40]
Not a serious issue but hxScout (Windows build 0.5.1) crashes when i run it next to Scout.
When i start Scout and have hxScout open, Scout complains about not being able to open port 7934, so maybe that's the problem?

**Comment by jcward** [comment]
Thanks. Issue #89 on the hxScout repo (not currently public...)

**Comment by jcward** [comment]
@sh-dave - one question: If you were using hxScout next to Scout, were you using Scout for profiling a SWF app and hxScout for profiling an hxcpp app?

**Comment by sh-dave** [comment]
Yes, i had Scout open yesterday while i profiled the flash build of my app, and then wanted to give hxScout a try for a native build today.
