### ISSUE TITLE
Misleading splashscreen message

### ISSUE THREAD

**Issue by sh-dave** [jcward/hxtelemetry#41]
Trying to solve #40 i was quite distracted by the 'build: unknown - requires cygwin + git' message in the splashscreen. I almost actually installed cygwin before i figured out i had Scout open.

Might be a good idea to remove that message (and probably show the the actual build number '0.5.1').

**Comment by jcward** [comment]
Thanks for your reports, I've transferred these bugs over to the hxScout repo. (I'll probably make that repo public again sometime soon.)
