### ISSUE TITLE
Haxe 4 compilation errors, Unknown identifier : validate_config, start_profiler_ do_advance_frame

### ISSUE THREAD

**Issue by jcward** [jcward/hxtelemetry#57]
When compiling with Haxe 4:

```
../../hxtelemetry/HxTelemetry.hx:132: characters 5-20 : Unknown identifier : validate_config
../../hxtelemetry/HxTelemetry.hx:144: characters 20-34 : Unknown identifier : start_profiler
../../hxtelemetry/HxTelemetry.hx:172: characters 5-21 : Unknown identifier : do_advance_frame
```

The issue is because of a change in static extension for Haxe 4, requiring a `this.` prefix on static extension for "this" class (see https://github.com/HaxeFoundation/haxe/issues/6036 and https://github.com/HaxeFoundation/haxe/issues/7190).

**Comment by jcward** [comment]
Ah, I was working on an old branch, already fixed by 6d1ec0d836

**Comment by jahndis** [comment]
Hey, just wanted to point out that this never made it into the latest version of hxtelemetry in haxelib. I was able to use haxelib git to use the master branch directly which works fine, but a regular install of the current latest version (0.3.5) still produces this error with the latest version of haxe (4.0.5 currently).
Not sure if master is in a state to be released? It's working for me right now fwiw. It might be worth updating the travis builds to run against the latest haxe version as well?

**Comment by jcward** [comment]
That's weird -- in adef28a0624417 I updated haxelib.json to 0.4.0 with the above changes. I usually do that and deploy to haxelib at the same time. Huh, well, I just pushed the update to 0.4.0.
