### ISSUE TITLE
hxscout.com is down

### ISSUE THREAD

**Issue by delahee** [jcward/hxtelemetry#64]
Hello I have interest in the project a few times a year but hxscout.com is down... can you write a tiny "get started" doc for when hxscout.com is down?

Thanks a lot <3

**Comment by jcward** [comment]
Hey David -- oops, brought it back (SSL cert expiration. Hmm, I thought that renew was cron'd.

Anyway, good idea on docs somewhere -- maybe github wiki or something.

**Comment by delahee** [comment]
Thanks!
